//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubleAtlas.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RubleAtlas.Infrastructure.Localization.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О проекте.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЦБ РФ.
        /// </summary>
        public static string Bank_of_Russia {
            get {
                return ResourceManager.GetString("Bank_of_Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} является важным денежным знаком, содержащим детальные исторические и географические достопримечательности, отражающие культурное наследие региона..
        /// </summary>
        public static string BanknoteDescriptionFormat {
            get {
                return ResourceManager.GetString("BanknoteDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкноты.
        /// </summary>
        public static string Banknotes_Page_Title {
            get {
                return ResourceManager.GetString("Banknotes_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Банкноты — это визитные карточки государства.».
        /// </summary>
        public static string BanknotesQuote {
            get {
                return ResourceManager.GetString("BanknotesQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архангельск.
        /// </summary>
        public static string City_Arkhangelsk {
            get {
                return ResourceManager.GetString("City.Arkhangelsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Челябинск.
        /// </summary>
        public static string City_Chelyabinsk {
            get {
                return ResourceManager.GetString("City.Chelyabinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Казань.
        /// </summary>
        public static string City_Kazan {
            get {
                return ResourceManager.GetString("City.Kazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хабаровск.
        /// </summary>
        public static string City_Khabarovsk {
            get {
                return ResourceManager.GetString("City.Khabarovsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красноярск.
        /// </summary>
        public static string City_Krasnoyarsk {
            get {
                return ResourceManager.GetString("City.Krasnoyarsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Москва.
        /// </summary>
        public static string City_Moscow {
            get {
                return ResourceManager.GetString("City.Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижний Новгород.
        /// </summary>
        public static string City_NizhnyNovgorod {
            get {
                return ResourceManager.GetString("City.NizhnyNovgorod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ржев.
        /// </summary>
        public static string City_Rzhev {
            get {
                return ResourceManager.GetString("City.Rzhev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санкт-Петербург.
        /// </summary>
        public static string City_SaintPetersburg {
            get {
                return ResourceManager.GetString("City.SaintPetersburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Салехард.
        /// </summary>
        public static string City_Salekhard {
            get {
                return ResourceManager.GetString("City.Salekhard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Саратов.
        /// </summary>
        public static string City_Saratov {
            get {
                return ResourceManager.GetString("City.Saratov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Севастополь.
        /// </summary>
        public static string City_Sevastopol {
            get {
                return ResourceManager.GetString("City.Sevastopol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соловецкий.
        /// </summary>
        public static string City_Solovetsky {
            get {
                return ResourceManager.GetString("City.Solovetsky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Циолковский.
        /// </summary>
        public static string City_Tsiolkovsky {
            get {
                return ResourceManager.GetString("City.Tsiolkovsky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тула.
        /// </summary>
        public static string City_Tula {
            get {
                return ResourceManager.GetString("City.Tula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Великий Новгород.
        /// </summary>
        public static string City_VelikyNovgorod {
            get {
                return ResourceManager.GetString("City.VelikyNovgorod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владивосток.
        /// </summary>
        public static string City_Vladivostok {
            get {
                return ResourceManager.GetString("City.Vladivostok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярославль.
        /// </summary>
        public static string City_Yaroslavl {
            get {
                return ResourceManager.GetString("City.Yaroslavl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Екатеринбург.
        /// </summary>
        public static string City_Yekaterinburg {
            get {
                return ResourceManager.GetString("City.Yekaterinburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монеты.
        /// </summary>
        public static string Coins_Page_Title {
            get {
                return ResourceManager.GetString("Coins_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памятные банкноты.
        /// </summary>
        public static string CommemorativeNotes {
            get {
                return ResourceManager.GetString("CommemorativeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крым 2015.
        /// </summary>
        public static string Crimea2015 {
            get {
                return ResourceManager.GetString("Crimea2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник данных.
        /// </summary>
        public static string Data_Source {
            get {
                return ResourceManager.GetString("Data_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        public static string DuisAute {
            get {
                return ResourceManager.GetString("DuisAute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..
        /// </summary>
        public static string ExcepteurSint {
            get {
                return ResourceManager.GetString("ExcepteurSint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор банкнот.
        /// </summary>
        public static string ExploreBanknotes {
            get {
                return ResourceManager.GetString("ExploreBanknotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнайте историю и достопримечательности, скрытые на денежных купюрах..
        /// </summary>
        public static string ExploreBanknotesSubtitle {
            get {
                return ResourceManager.GetString("ExploreBanknotesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярные достопримечательности.
        /// </summary>
        public static string FeaturedLandmarks {
            get {
                return ResourceManager.GetString("FeaturedLandmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти.
        /// </summary>
        public static string GoToPlace {
            get {
                return ResourceManager.GetString("GoToPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История и дизайн.
        /// </summary>
        public static string HistoryAndDesign {
            get {
                return ResourceManager.GetString("HistoryAndDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовня Параскевы Пятницы.
        /// </summary>
        public static string Landmark_RUB10_1997_Obverse_KrasnoyarskChapel {
            get {
                return ResourceManager.GetString("Landmark.RUB10.1997.Obverse.KrasnoyarskChapel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммунальный мост.
        /// </summary>
        public static string Landmark_RUB10_1997_Obverse_YeniseyBridge {
            get {
                return ResourceManager.GetString("Landmark.RUB10.1997.Obverse.YeniseyBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Красноярская ГЭС.
        /// </summary>
        public static string Landmark_RUB10_1997_Reverse_KrasnoyarskHydroDam {
            get {
                return ResourceManager.GetString("Landmark.RUB10.1997.Reverse.KrasnoyarskHydroDam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрига Большого театра.
        /// </summary>
        public static string Landmark_RUB100_1997_Obverse_QuadrigaBolshoi {
            get {
                return ResourceManager.GetString("Landmark.RUB100.1997.Obverse.QuadrigaBolshoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большой театр.
        /// </summary>
        public static string Landmark_RUB100_1997_Reverse_BolshoiTheatre {
            get {
                return ResourceManager.GetString("Landmark.RUB100.1997.Reverse.BolshoiTheatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главный корпус МГУ.
        /// </summary>
        public static string Landmark_RUB100_2022_Obverse_MGUMainBuilding {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Obverse.MGUMainBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останкинская телебашня.
        /// </summary>
        public static string Landmark_RUB100_2022_Obverse_OstankinskayaTower {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Obverse.OstankinskayaTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаболовская (Шуховская) телебашня.
        /// </summary>
        public static string Landmark_RUB100_2022_Obverse_ShukhonTower {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Obverse.ShukhonTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасская башня.
        /// </summary>
        public static string Landmark_RUB100_2022_Obverse_SpasskayaTower {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Obverse.SpasskayaTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стеклянный купол из парка «Зарядье».
        /// </summary>
        public static string Landmark_RUB100_2022_Obverse_ZaryadyeParkGlassDome {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Obverse.ZaryadyeParkGlassDome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музей-заповедник «Куликово поле».
        /// </summary>
        public static string Landmark_RUB100_2022_Reverse_KulikovoField {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Reverse.KulikovoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ржевский мемориал Советскому Cолдату.
        /// </summary>
        public static string Landmark_RUB100_2022_Reverse_RzhevMemorial {
            get {
                return ResourceManager.GetString("Landmark.RUB100.2022.Reverse.RzhevMemorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часовня Казанской Богоматери.
        /// </summary>
        public static string Landmark_RUB1000_1997_Obverse_YaroslavlChapel {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.1997.Obverse.YaroslavlChapel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ярославский кремль.
        /// </summary>
        public static string Landmark_RUB1000_1997_Obverse_YaroslavlKremlin {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.1997.Obverse.YaroslavlKremlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памятник Ярославу Мудрому.
        /// </summary>
        public static string Landmark_RUB1000_1997_Obverse_YaroslavTheWiseMonument {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.1997.Obverse.YaroslavTheWiseMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Церковь Иоанна Предтечи.
        /// </summary>
        public static string Landmark_RUB1000_1997_Reverse_ChurchOfJohnThePrecursor {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.1997.Reverse.ChurchOfJohnThePrecursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никольская башня Нижегородского кремля.
        /// </summary>
        public static string Landmark_RUB1000_2025_Obverse_NikolskayaTowerNNKremlin {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.2025.Obverse.NikolskayaTowerNNKremlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижегородская ярмарка.
        /// </summary>
        public static string Landmark_RUB1000_2025_Obverse_NizhnyNovgorodFair {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.2025.Obverse.NizhnyNovgorodFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стадион «Нижний Новгород».
        /// </summary>
        public static string Landmark_RUB1000_2025_Obverse_NizhnyNovgorodStadium {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.2025.Obverse.NizhnyNovgorodStadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дворец земледельцев.
        /// </summary>
        public static string Landmark_RUB1000_2025_Reverse_PalaceOfFarmers {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.2025.Reverse.PalaceOfFarmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Саратовский автомобильный мост.
        /// </summary>
        public static string Landmark_RUB1000_2025_Reverse_SaratovAutomobileBridge {
            get {
                return ResourceManager.GetString("Landmark.RUB1000.2025.Reverse.SaratovAutomobileBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памятник затопленным кораблям.
        /// </summary>
        public static string Landmark_RUB200_2017_Obverse_MonumentToSunkenShips {
            get {
                return ResourceManager.GetString("Landmark.RUB200.2017.Obverse.MonumentToSunkenShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Херсонес Таврический.
        /// </summary>
        public static string Landmark_RUB200_2017_Reverse_TauricChersonese {
            get {
                return ResourceManager.GetString("Landmark.RUB200.2017.Reverse.TauricChersonese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский мост.
        /// </summary>
        public static string Landmark_RUB2000_2017_Obverse_RusskyBridge {
            get {
                return ResourceManager.GetString("Landmark.RUB2000.2017.Obverse.RusskyBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Космодром «Восточный».
        /// </summary>
        public static string Landmark_RUB2000_2017_Reverse_VostochnyCosmodrome {
            get {
                return ResourceManager.GetString("Landmark.RUB2000.2017.Reverse.VostochnyCosmodrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памятник «Тысячелетие России».
        /// </summary>
        public static string Landmark_RUB5_1997_Obverse_MillenniumOfRussia {
            get {
                return ResourceManager.GetString("Landmark.RUB5.1997.Obverse.MillenniumOfRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Софийский собор.
        /// </summary>
        public static string Landmark_RUB5_1997_Obverse_SophiaCathedral {
            get {
                return ResourceManager.GetString("Landmark.RUB5.1997.Obverse.SophiaCathedral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стена Новгородского кремля.
        /// </summary>
        public static string Landmark_RUB5_1997_Reverse_NovgorodKremlinWall {
            get {
                return ResourceManager.GetString("Landmark.RUB5.1997.Reverse.NovgorodKremlinWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петропавловская крепость.
        /// </summary>
        public static string Landmark_RUB50_1997_Obverse_PeterAndPaulFortress {
            get {
                return ResourceManager.GetString("Landmark.RUB50.1997.Obverse.PeterAndPaulFortress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ростральная колонна.
        /// </summary>
        public static string Landmark_RUB50_1997_Obverse_RostralColumn {
            get {
                return ResourceManager.GetString("Landmark.RUB50.1997.Obverse.RostralColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здание Биржи.
        /// </summary>
        public static string Landmark_RUB50_1997_Reverse_StockExchange {
            get {
                return ResourceManager.GetString("Landmark.RUB50.1997.Reverse.StockExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памятник Петру I.
        /// </summary>
        public static string Landmark_RUB500_1997_Obverse_PeterTheGreatMonument {
            get {
                return ResourceManager.GetString("Landmark.RUB500.1997.Obverse.PeterTheGreatMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Морской-речной порт.
        /// </summary>
        public static string Landmark_RUB500_1997_Obverse_SeaRiverPort {
            get {
                return ResourceManager.GetString("Landmark.RUB500.1997.Obverse.SeaRiverPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соловецкий монастырь.
        /// </summary>
        public static string Landmark_RUB500_1997_Obverse_SolovetskyMonastery {
            get {
                return ResourceManager.GetString("Landmark.RUB500.1997.Obverse.SolovetskyMonastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Набережная Адмирала Невельского.
        /// </summary>
        public static string Landmark_RUB5000_1997_Obverse_KhabarovskEmbankment {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.1997.Obverse.KhabarovskEmbankment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Памятник Муравьёву-Амурскому.
        /// </summary>
        public static string Landmark_RUB5000_1997_Obverse_MuravyovAmurskyMonument {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.1997.Obverse.MuravyovAmurskyMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мост через Амур.
        /// </summary>
        public static string Landmark_RUB5000_1997_Reverse_AmurRiverBridge {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.1997.Reverse.AmurRiverBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр Екатеринбурга.
        /// </summary>
        public static string Landmark_RUB5000_2023_Obverse_CityCenter {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.2023.Obverse.CityCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стела «Европа–Азия».
        /// </summary>
        public static string Landmark_RUB5000_2023_Obverse_EuropeAsiaMonument {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.2023.Obverse.EuropeAsiaMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колесо обозрения.
        /// </summary>
        public static string Landmark_RUB5000_2023_Obverse_FerrisWheel {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.2023.Obverse.FerrisWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дом Н. И. Севастьянова.
        /// </summary>
        public static string Landmark_RUB5000_2023_Obverse_SevastyanovHouse {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.2023.Obverse.SevastyanovHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66-я параллель.
        /// </summary>
        public static string Landmark_RUB5000_2023_Reverse_66thParallel {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.2023.Reverse.66thParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монумент «Сказ об Урале».
        /// </summary>
        public static string Landmark_RUB5000_2023_Reverse_UralMonument {
            get {
                return ResourceManager.GetString("Landmark.RUB5000.2023.Reverse.UralMonument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..
        /// </summary>
        public static string LoremIpsumLong {
            get {
                return ResourceManager.GetString("LoremIpsumLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim..
        /// </summary>
        public static string LoremIpsumShort {
            get {
                return ResourceManager.GetString("LoremIpsumShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Потерянные» банкноты.
        /// </summary>
        public static string LostBanknotes {
            get {
                return ResourceManager.GetString("LostBanknotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string Map_Page_Title {
            get {
                return ResourceManager.GetString("Map_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — это известная достопримечательность, признанная за свою историческую, архитектурную и культурную значимость..
        /// </summary>
        public static string PlaceDescriptionFormat {
            get {
                return ResourceManager.GetString("PlaceDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали места.
        /// </summary>
        public static string PlaceDetails {
            get {
                return ResourceManager.GetString("PlaceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RubleAtlas.
        /// </summary>
        public static string Project_Title {
            get {
                return ResourceManager.GetString("Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать больше....
        /// </summary>
        public static string Read_More {
            get {
                return ResourceManager.GetString("Read_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10₽ 1997.
        /// </summary>
        public static string rub_10_1997 {
            get {
                return ResourceManager.GetString("rub-10-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100₽ 1997.
        /// </summary>
        public static string rub_100_1997 {
            get {
                return ResourceManager.GetString("rub-100-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100₽ 2014.
        /// </summary>
        public static string rub_100_2014_alt {
            get {
                return ResourceManager.GetString("rub-100-2014-alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100₽ 2015.
        /// </summary>
        public static string rub_100_2015_alt {
            get {
                return ResourceManager.GetString("rub-100-2015-alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100₽ 2018.
        /// </summary>
        public static string rub_100_2018_alt {
            get {
                return ResourceManager.GetString("rub-100-2018-alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100₽ 2022.
        /// </summary>
        public static string rub_100_2022 {
            get {
                return ResourceManager.GetString("rub-100-2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000₽ 1995.
        /// </summary>
        public static string rub_1000_1995_alt {
            get {
                return ResourceManager.GetString("rub-1000-1995-alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000₽ 1997.
        /// </summary>
        public static string rub_1000_1997 {
            get {
                return ResourceManager.GetString("rub-1000-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000₽ 2023.
        /// </summary>
        public static string rub_1000_2023_alt {
            get {
                return ResourceManager.GetString("rub-1000-2023-alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000₽ 2025.
        /// </summary>
        public static string rub_1000_2025 {
            get {
                return ResourceManager.GetString("rub-1000-2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200₽ 2017.
        /// </summary>
        public static string rub_200_2017 {
            get {
                return ResourceManager.GetString("rub-200-2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000₽ 2017.
        /// </summary>
        public static string rub_2000_2017 {
            get {
                return ResourceManager.GetString("rub-2000-2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5₽ 1997.
        /// </summary>
        public static string rub_5_1997 {
            get {
                return ResourceManager.GetString("rub-5-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50₽ 1997.
        /// </summary>
        public static string rub_50_1997 {
            get {
                return ResourceManager.GetString("rub-50-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500₽ 1997.
        /// </summary>
        public static string rub_500_1997 {
            get {
                return ResourceManager.GetString("rub-500-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000₽ 1997.
        /// </summary>
        public static string rub_5000_1997 {
            get {
                return ResourceManager.GetString("rub-5000-1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000₽ 2023.
        /// </summary>
        public static string rub_5000_2023 {
            get {
                return ResourceManager.GetString("rub-5000-2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банкнота {0} рублей.
        /// </summary>
        public static string RubleBanknoteAlt {
            get {
                return ResourceManager.GetString("RubleBanknoteAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волокна: цветные (красные, синие и серые).
        /// </summary>
        public static string Security_Fibres_ColouredRedBlueAndGrey {
            get {
                return ResourceManager.GetString("Security.Fibres.ColouredRedBlueAndGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волокна: двух типов.
        /// </summary>
        public static string Security_Fibres_TwoTypes {
            get {
                return ResourceManager.GetString("Security.Fibres.TwoTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волокна: двух типов красно-синие сегменты и серые.
        /// </summary>
        public static string Security_Fibres_TwoTypes_RedBlueSegmentsAndGrey {
            get {
                return ResourceManager.GetString("Security.Fibres.TwoTypes.RedBlueSegmentsAndGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Машиносчитываемые признаки.
        /// </summary>
        public static string Security_MachineReadableFeatures {
            get {
                return ResourceManager.GetString("Security.MachineReadableFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бумага: Белый хлопок.
        /// </summary>
        public static string Security_Paper_WhiteCotton {
            get {
                return ResourceManager.GetString("Security.Paper.WhiteCotton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бумага: Белый хлопок с полимерной пропиткой.
        /// </summary>
        public static string Security_Paper_WhiteCotton_PolymerImpregnated {
            get {
                return ResourceManager.GetString("Security.Paper.WhiteCotton.PolymerImpregnated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR-код: на страницу Банка России.
        /// </summary>
        public static string Security_QRCode_ToCBRInfo {
            get {
                return ResourceManager.GetString("Security.QRCode.ToCBRInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тактильный элемент: выпуклая печать.
        /// </summary>
        public static string Security_Tactile_RaisedPrint {
            get {
                return ResourceManager.GetString("Security.Tactile.RaisedPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитная нить: голографическая оконная 5,5 мм фигурное окно.
        /// </summary>
        public static string Security_Thread_Holographic_Windowed5_5mm_ShapedWindow {
            get {
                return ResourceManager.GetString("Security.Thread.Holographic.Windowed5_5mm.ShapedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитная нить: голографическая 3 мм.
        /// </summary>
        public static string Security_Thread_Holographic3mm {
            get {
                return ResourceManager.GetString("Security.Thread.Holographic3mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитная нить: оконная металлизированная.
        /// </summary>
        public static string Security_Thread_WindowedMetallized {
            get {
                return ResourceManager.GetString("Security.Thread.WindowedMetallized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два серийных номера: Серия: 2 буквы + 7 цифр.
        /// </summary>
        public static string Security_TwoSerialNumbers_Series2LettersPlus7Digits {
            get {
                return ResourceManager.GetString("Security.TwoSerialNumbers.Series2LettersPlus7Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два серийных номера: Серия: 2 буквы + 9 цифр Ориентация по короткой и длинной сторонам.
        /// </summary>
        public static string Security_TwoSerialNumbers_Series2LettersPlus9Digits_Orientations_ShortAndLongSides {
            get {
                return ResourceManager.GetString("Security.TwoSerialNumbers.Series2LettersPlus9Digits.Orientations.ShortAndLongSide" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водяной знак: многотоновый и с высветлением.
        /// </summary>
        public static string Security_Watermark_MultitoneAndHighlight {
            get {
                return ResourceManager.GetString("Security.Watermark.MultitoneAndHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия {0} года.
        /// </summary>
        public static string SeriesFormat {
            get {
                return ResourceManager.GetString("SeriesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значимость.
        /// </summary>
        public static string Significance {
            get {
                return ResourceManager.GetString("Significance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Олимпиада в Сочи 2014.
        /// </summary>
        public static string Sochi2014 {
            get {
                return ResourceManager.GetString("Sochi2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 10 рублей (1997).
        /// </summary>
        public static string Trivia_RUB10_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB10.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 100 рублей (1997).
        /// </summary>
        public static string Trivia_RUB100_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB100.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 100 рублей (2022).
        /// </summary>
        public static string Trivia_RUB100_2022 {
            get {
                return ResourceManager.GetString("Trivia.RUB100.2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 1000 рублей (1997).
        /// </summary>
        public static string Trivia_RUB1000_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB1000.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 1000 рублей (2025).
        /// </summary>
        public static string Trivia_RUB1000_2025 {
            get {
                return ResourceManager.GetString("Trivia.RUB1000.2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 200 рублей (2017).
        /// </summary>
        public static string Trivia_RUB200_2017 {
            get {
                return ResourceManager.GetString("Trivia.RUB200.2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 2000 рублей (2017).
        /// </summary>
        public static string Trivia_RUB2000_2017 {
            get {
                return ResourceManager.GetString("Trivia.RUB2000.2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 5 рублей (1997).
        /// </summary>
        public static string Trivia_RUB5_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB5.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 50 рублей (1997).
        /// </summary>
        public static string Trivia_RUB50_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB50.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 500 рублей (1997).
        /// </summary>
        public static string Trivia_RUB500_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB500.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 5000 рублей (1997).
        /// </summary>
        public static string Trivia_RUB5000_1997 {
            get {
                return ResourceManager.GetString("Trivia.RUB5000.1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Факты: 5000 рублей (2023).
        /// </summary>
        public static string Trivia_RUB5000_2023 {
            get {
                return ResourceManager.GetString("Trivia.RUB5000.2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чемпионат мира по футболу 2018.
        /// </summary>
        public static string WorldCup2018 {
            get {
                return ResourceManager.GetString("WorldCup2018", resourceCulture);
            }
        }
    }
}
